Fork.feat.header&home
CharlieEtienne/material-github pull request #51
Opened 2020-10-29 15:53 UTC by miiwu

- Header
- Home, Repositories
- Home, Recent activity
- Home, All activity
- Home, Explore repositories

2020-10-29 15:54 UTC, miiwu commented
@CharlieEtienne 
Hi, Is this ok?

2020-10-29 16:54 UTC, CharlieEtienne requested changes

2020-10-29 16:54 UTC, CharlieEtienne commented on material-github.user.css
> +	}
please delete that, it causes a padding issue on home page
![2020-10-29_17h36_21](https://user-images.githubusercontent.com/9772943/97604321-9fa1a500-1a0d-11eb-8409-b79157584478.png)

2020-10-29 16:54 UTC, CharlieEtienne commented on material-github.user.css
> +	}
Could you explain what you are trying to achieve here? I don't see any difference when I test your code

2020-10-29 16:54 UTC, CharlieEtienne commented on material-github.user.css
> +	}
Honestly, I prefer the current borders, more discrete.

2020-10-29 16:54 UTC, CharlieEtienne commented on material-github.user.css
> +	}
You can't do that. You are targeting all elements with padding and margin = 2. It's unpredictable. 
Please find another way.

2020-10-30 03:46 UTC, miiwu commented
@CharlieEtienne 
Sorry, it would be delayed for several monthes, until i'm leisure.
Or you can close it.

- - -

I'm hobbyist.
I am applying myself to my own major, workingly and intently. 
There may be too much conflicts due to my knowledge shortage, or, github changes itself, just maybe.

2020-12-26 23:36 UTC, closed without merging